### ISSUE TITLE
getting issue in the sent sms

### ISSUE THREAD

**Issue by imanmay2** [manmay2/XChat#6]
ISSUE :
            TRY PROPER TYPING IN THE TEXTBOX (LIKE HELLO MANMAY....5 TO 8 TIMES) AND CLICK THE SEND BUTTON...
            AFTER THE MESSAGE HAS BEEN SENT....TRY NOTICING THE ISSUE....IF THE MESSAGE IS DISPLAYED LIKE (HLEOL MANMYA), IN THE SENT SECTION ,SOMETHING LIKE THIS....
            TRY USING IN YOUR SYSTEM TOO...
            IF NO ISSUE FROM YOUR SIDE..
            LET ME KNOW...
            
THANKS FOR GIVING YOUR VALUABLE TIME.
Manmay Chakraborty

**Comment by SoumadeepChoudhury** [comment]
# #Issue 6
Issue / Error Noticed....
Fixing it soon...
Will leave a comment here.

Thank You.
Soumadeep Choudhury

**Comment by SoumadeepChoudhury** [comment]
Fixed bug
